project_id = "isywidnfnjhtydmdfgtk"

[functions.translate]
verify_jwt = false

[functions.ask-anything]
verify_jwt = false

[functions.s3-upload]
verify_jwt = false

[functions.migrate-storage]
verify_jwt = false
